Use /system directly, don't bind mount off /data

diff --git a/init b/init
--- a/init
+++ b/init
@@ -75,7 +75,7 @@ if [ $notnand = "1" ] ; then
     if [ -d /sys/block/mmcblk0/mmcblk0p4 ] && /bin/grep -q -v no_partitions /proc/cmdline ; then
 	    echo "Using partitioned system"
 	    /bin/e2fsck -y /dev/block/mmcblk0p3
-	    mount -t ext2 -o ro,relatime /dev/block/mmcblk0p3 /system
+	    mount -t ext2 -o relatime /dev/block/mmcblk0p3 /system
 	    /bin/e2fsck -y /dev/block/mmcblk0p4
 	    mount -t ext2 -o relatime /dev/block/mmcblk0p4 /data
     else
@@ -93,27 +93,11 @@ if [ $notnand = "1" ] ; then
             e2fsck -y /dev/block/loop0
             mount -t ext2 -o relatime /dev/block/loop0 /data
 
-            if      [ -f $card/system.ext2 ] ; then
-                    echo "Using uncompressed system"
-                    losetup /dev/block/loop1 $card/system.ext2
-                    [ $? -eq 0 ] || fail "Failed to reach system.ext2 on SD Card"
-                    e2fsck -y /dev/block/loop1
-                    mount -t ext2 -o relatime /dev/block/loop1 /system
+            losetup /dev/block/loop1 $card/system.ext2
+            [ $? -eq 0 ] || fail "Failed to reach system.ext2 on SD Card"
+            e2fsck -y /dev/block/loop1
+            mount -t ext2 -o relatime /dev/block/loop1 /system
 		    [ $? -eq 0 ] || fail "Failed to mount /system"
-            elif    
-		    [ -f $card/system.sqsh ] ; then
-                    echo "Using SquashFS system"
-                    losetup /dev/block/loop1 $card/system.sqsh
-                    [ $? -eq 0 ] || fail "Failed to find system.sqsh on SD Card"
-                    mount -t squashfs -o ro,relatime /dev/block/loop1 /system
-                    [ $? -eq 0 ] || fail "Failed to mount /system"
-		    SQUASH=1
-            else
-                    losetup /dev/block/loop1 $card/system.img
-                    [ $? -eq 0 ] || fail "Failed to find system.img on SD Card"
-                    mount -t cramfs -o ro,relatime /dev/block/loop1 /system
-                    [ $? -eq 0 ] || fail "Failed to mount /system"
-            fi
     fi
 fi
 
@@ -139,7 +123,7 @@ if [ -d $card/AndroidApps ] ; then
                 mkdir -m 0771 /data/app
 		chown -R 1000:1000 /data/app
         fi
-	(cd $card/AndroidApps; for i in *; do if [ "$i" -nt "/data/app/$i" ]; then \
+	(cd $card/AndroidApps; for i in *; do if [ ! -f "/data/app/$i" -o "$i" -nt "/data/app/$i" ]; then \
 		cp "$i" /data/app; fi done)
 fi
 
@@ -147,41 +131,27 @@ if [ ! -d $card/media ] ; then
         echo You have no media folder, please extract the resources to your SD card android folder
 fi
 
-NEW_SYSTEM=0
-NEW_ROOT=0
-
-if [ ! -d /data/etc ]; then
-	/bin/mkdir -m 0755 /data/etc
-	NEW_SYSTEM=1
+CHK_ROOT=etc/wifi/Fw1251r1c.bin
+if [ ! -f /system/$CHK_ROOT -o /init.$CHK_ROOT -nt /system/$CHK_ROOT ]; then
 	NEW_ROOT=1
 else
-	CHK_SYS=etc/event-log-tags
-	if [ ! -f /data/$CHK_SYS -o /system/$CHK_SYS -nt /data/$CHK_SYS ]; then
-		NEW_SYSTEM=1
-	fi
-	CHK_ROOT=etc/wifi/Fw1251r1c.bin
-	if [ ! -f /data/$CHK_ROOT -o /init.$CHK_ROOT -nt /data/$CHK_ROOT ]; then
-		NEW_ROOT=1
-	fi
+	NEW_ROOT=0
 fi
 
-if [ $NEW_SYSTEM -eq 1 ]; then
-	cp -ar /system/etc/* /data/etc
-fi
 if [ $NEW_ROOT -eq 1 ]; then
-	cp -ar /init.etc/* /data/etc
+	cp -ar /init.etc/* /system/etc
 fi
 
 LCDDENSITY=`/bin/grep -o "lcd.density=.*" /proc/cmdline | /bin/sed -e "s/.*lcd.density=//g" -e "s/ .*//g"`
 
 if [ "$LCDDENSITY" != "" ] ; then
-	DENS2=`grep lcd_density /data/etc/default.prop | sed -e 's/.*=//'`
+	DENS2=`grep lcd_density /system/etc/default.prop | sed -e 's/.*=//'`
 	if [ "$LCDDENSITY" != "$DENS2" ]; then
 		echo Setting ro.sf.lcd_density=$LCDDENSITY
 		if [ -z "$DENS2" ]; then
-			echo "ro.sf.lcd_density=$LCDDENSITY" >> /data/etc/default.prop
+			echo "ro.sf.lcd_density=$LCDDENSITY" >> /system/etc/default.prop
 		else
-			sed -i /lcd_density/s/=.*/=$LCDDENSITY/ /data/etc/default.prop
+			sed -i /lcd_density/s/=.*/=$LCDDENSITY/ /system/etc/default.prop
 		fi
 	fi
 fi
@@ -286,20 +256,10 @@ elif [ -f /system/froyo.build ] ; then
 	RCCONFIG="froyo"
 	mount --bind /lib/froyo/hw /system/lib/hw
 
-	# vold: Fix sdcard device location for CDMA boards (thanks paalsteek)
-	if [ $NEW_SYSTEM -eq 1 -a -d /sys/devices/platform/msm_sdcc.3 ]; then
-		/bin/sed -i -e 's:/devices/platform/msm_sdcc\.2:/devices/platform/msm_sdcc.3:g' /data/etc/vold.fstab
-	fi
-
 elif [ -f /system/gingerbread.build ] ; then
 	echo "Gingerbread build detected"
 	RCSCRIPT="gingerbread"
 	RCCONFIG="gingerbread"
-
-	# vold: Fix sdcard device location for CDMA boards (thanks paalsteek)
-	if [ $NEW_SYSTEM -eq 1 -a -d /sys/devices/platform/msm_sdcc.3 ]; then
-		/bin/sed -i -e 's:/devices/platform/msm_sdcc\.2:/devices/platform/msm_sdcc.3:g' /data/etc/vold.fstab
-	fi
 
 elif [ -f /system/tattoo.build ] ; then
 	echo "Tattoo build detected"
@@ -356,14 +316,33 @@ if [ $KAISER -eq 1 ] ; then
 	RCSCRIPT="$RCSCRIPT.kaiser"
 fi
 
-if [ $NEW_ROOT -eq 1 -a $XPERIA -eq 1 ] ; then
-	echo "ro.sf.hwrotation=180" >> /data/etc/default.prop
+if [ "$LCDDENSITY" != "" ] ; then
+	DENS2=`grep lcd_density /system/etc/default.prop | sed -e 's/.*=//'`
+	if [ "$LCDDENSITY" != "$DENS2" ]; then
+		echo Setting ro.sf.lcd_density=$LCDDENSITY
+		if [ -z "$DENS2" ]; then
+			echo "ro.sf.lcd_density=$LCDDENSITY" >> /system/etc/default.prop
+		else
+			sed -i /lcd_density/s/=.*/=$LCDDENSITY/ /system/etc/default.prop
+		fi
+	fi
 fi
-echo "using /init.$RCSCRIPT.rc as init.rc"
+if [ $XPERIA -eq 1 ] ; then
+	ROT=`grep hwrotation /system/etc/default.prop | sed -e 's/.*=//'`
+	if [ "$ROT" != 180 ]; then
+		echo Setting ro.sf.hwrotation=180
+		if [ -z "$ROT" ]; then
+			echo "ro.sf.hwrotation=180" >> /system/etc/default.prop
+		else
+			sed -i /hwrotation/s/=.*/=180/ /system/etc/default.prop
+		fi
+	fi
+fi
 echo "using $card/conf/$RCCONFIG.user.conf"
 
 if [ $NEW_ROOT -eq 1 ]; then
-	cp "/init.cfg/init.$RCSCRIPT.rc" /data/etc/init.rc
+	echo "using /init.$RCSCRIPT.rc as init.rc"
+	cp "/init.cfg/init.$RCSCRIPT.rc" /system/etc/init.rc
 fi
 
 #Assume this rootfs.img will be used only on "good" devices
@@ -382,29 +361,23 @@ if [ -d /data/dropbear/ ] ; then
 fi
 
 if [ "$WIFI_TI" = "1" ] || [ "$WIFI_BCM" = "1" ];then
-	if [ -e "$card/modules-$(uname -r).tar.gz" ] && ! `strings /data/modules/mac80211.ko 2>/dev/null | grep -q "vermagic=$(uname -r)"`; then
+	if [ -e "$card/modules-$(uname -r).tar.gz" ] && ! `strings /lib/modules/mac80211.ko 2>/dev/null | grep -q "vermagic=$(uname -r)"`; then
 		echo "Installing $card/modules-$(uname -r).tar.gz"
-		if [ ! -d "/data/modules" ] ; then
-			mkdir /data/modules
-		fi
-		tar xzf $card/modules-$(uname -r).tar.gz -C /data/modules
-		ln -s /data/modules /data/modules/`uname -r`
+		tar xzf $card/modules-$(uname -r).tar.gz -C /lib/modules
+		ln -s /lib/modules /lib/modules/`uname -r`
 	else
 		echo "Modules already unpacked for this kernel version -- skipping installation of $card/modules-$(uname -r).tar.gz"
 	fi
 
-#	mount --bind /data/modules /lib/modules
-	mount --bind /data/modules /system/lib/modules
-
-	if [ -f /data/etc/wifi/wlan.ko ]; then
-	cp -R /data/etc/wifi/* /data/modules/
-	rm /data/etc/wifi/wlan.ko
+	if [ -f /system/etc/wifi/wlan.ko ]; then
+	cp -R /system/etc/wifi/* /lib/modules/
+	rm /system/etc/wifi/wlan.ko
 	depmod
 	fi
 
-	if [ "`grep -c ^wifi /data/etc/default.prop`" != "2" ]; then
-		echo "wifi.interface = wlan0" >> /data/etc/default.prop
-		echo "wifi.supplicant_scan_interval = 45" >> /data/etc/default.prop
+	if [ "`grep -c ^wifi /system/etc/default.prop`" != "2" ]; then
+		echo "wifi.interface = wlan0" >> /system/etc/default.prop
+		echo "wifi.supplicant_scan_interval = 45" >> /system/etc/default.prop
 	fi
 fi
 
@@ -420,7 +393,7 @@ if [ $NEW_ROOT -eq 1 ]; then
 	else
 		PPPDEV=/dev/smd1
 	fi
-	sed -i s,PPPDEV,$PPPDEV, /data/etc/init.rc
+	sed -i s,PPPDEV,$PPPDEV, /system/etc/init.rc
 fi
 
 
@@ -429,23 +402,21 @@ if [ "$WIFI_BCM" = "1" ] ;then
 
 	if [ $NEW_ROOT -eq 1 ]; then
 		# init.rc: fix wpa_supplicant service
-		sed -i s/-Dtiwlan0/-Dwext/ /data/etc/init.rc
+		sed -i s/-Dtiwlan0/-Dwext/ /system/etc/init.rc
 
 		# init.rc:
-		sed -i s/user\ wifi/#user\ wifi/ /data/etc/init.rc
-		sed -i s/group\ wifi/#group\ wifi/ /data/etc/init.rc
+		sed -i s/user\ wifi/#user\ wifi/ /system/etc/init.rc
+		sed -i s/group\ wifi/#group\ wifi/ /system/etc/init.rc
 	fi
 
 	# extract nvram (todo: clean this up/integrate with TI calibration)
 	if [ ! -e /data/wifi-nvram.txt ]; then
+		insmod /lib/modules/mtdchar.ko
+		mknod /dev/mtd0ro c 90 1
 		for SKIP in 5744 4736;do
-			insmod /lib/modules/mtdchar.ko
-			mknod /dev/mtd0ro c 90 1
 			mkdir /lib/modules/$(uname -r)
 
 			dd if=/dev/mtd0ro of=/tmp/tempcal bs=8192 count=1 skip=$SKIP
-			rm /dev/mtd0ro
-			rmmod mtdchar
 			rmdir /lib/modules/$(uname -r)
 			dd if=/tmp/tempcal of=/data/wifi-nvram.txt bs=1 count=466
 			rm /tmp/tempcal
@@ -454,6 +425,8 @@ if [ "$WIFI_BCM" = "1" ] ;then
 				break
 			fi;
 		done
+		rm /dev/mtd0ro
+		rmmod mtdchar
 		if [ "$SKIP" = "5744" ];then
 			echo "CDMA Rhodium detected"
 		fi;
@@ -464,7 +437,7 @@ if [ "$WIFI_BCM" = "1" ] ;then
 	fi
 fi
 
-for i in local.prop eri.xml; do
+for i in local.prop eri.xml serialno; do
 	if [ -f "$card/$i" ]; then
 		if [ ! -f /data/$i -o "$card/$i" -nt /data/$i ]; then
 			cp "$card/$i" /data/$i
@@ -493,107 +466,101 @@ KBD=`sed 's/.*physkeyboard=\([0-9a-z_]*\).*/\1/' /proc/cmdline`
 case "$KBD" in
     fuse)
 	echo "USING RAPH110|FUZE LAYOUT"
-	cp -f /init.etc/keymaps/fuze_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/fuze_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/fuze_raph_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+	cp -f /init.etc/keymaps/fuze_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/fuze_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/fuze_raph_navi_pad.kl /system/usr/keylayout/raph_navi_pad.kl
 	;;
     raph)
 	echo "USING NEW RAPH LAYOUT"
-        cp -f /init.etc/keymaps/raphfix_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/raphfix_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     nordic_raph)
 	echo "USING NEW NORDIC RAPH LAYOUT"
-        cp -f /init.etc/keymaps/raphfix_microp-keypad-swedish.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/raphfix_microp-keypad-swedish.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     german_raph)
 	echo "USING NEW GERMAN RAPH LAYOUT"
-        cp -f /init.etc/keymaps/microp-german.keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/microp-german.keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     swiss_raph)
 	echo "USING NEW SWISS RAPH LAYOUT"
-        cp -f /init.etc/keymaps/microp-swiss.keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/microp-swiss.keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     tilt2)
 	echo "USING EXPERIMENTAL TILT2 LAYOUT"
-        cp -f /init.etc/keymaps/tilt2_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/tilt2_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/tilt2_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/tilt2_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/tilt2_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/tilt2_navi_pad.kl /system/usr/keylayout/raph_navi_pad.kl
 	;;
     rhod210)
 	echo "USING EXPERIMENTAL RHOD210 LAYOUT"
-        cp -f /init.etc/keymaps/rhod210_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod210_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod210_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod210_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod210_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod210_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod100_de)
 	echo "USING RHOD100 DE LAYOUT"
-        cp -f /init.etc/keymaps/rhod100_de_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod100_de_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod100_de_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod100_de_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod100_de_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod100_de_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod100_fr)
 	echo "USING RHOD100 FR LAYOUT"
-        cp -f /init.etc/keymaps/rhod100_fr_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod100_fr_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod100_fr_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod100_fr_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod100_fr_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod100_fr_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod100_it)
 	echo "USING RHOD100 IT LAYOUT"
-        cp -f /init.etc/keymaps/rhod100_it_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod100_it_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod100_it_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod100_it_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod100_it_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod100_it_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod100_uk)
 	echo "USING RHOD100 UK LAYOUT"
-        cp -f /init.etc/keymaps/rhod100_uk_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod100_uk_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod100_uk_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod100_uk_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod100_uk_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod100_uk_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod100_nordic)
 	echo "USING RHOD100 NORDIC LAYOUT"
-        cp -f /init.etc/keymaps/rhod100_nordic_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/rhod100_nordic_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/rhod100_nordic_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/rhod100_nordic_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/rhod100_nordic_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/rhod100_nordic_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
     rhod400)
         echo "USING EXPERIMENTAL RHOD400 LAYOUT"
-        cp -f /init.etc/keymaps/rhod400_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-        cp -f /init.etc/keymaps/rhod400_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-        cp -f /init.etc/keymaps/rhod400_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl #does not exist, just following example
+        cp -f /init.etc/keymaps/rhod400_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+        cp -f /init.etc/keymaps/rhod400_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/rhod400_navi_pad.kl /system/usr/keylayout/gpio-keys.kl #does not exist, just following example
 	;;
     rhod500)
         echo "USING EXPERIMENTAL RHOD500 LAYOUT"
-        cp -f /init.etc/keymaps/rhod500_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-        cp -f /init.etc/keymaps/rhod500_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-        cp -f /init.etc/keymaps/rhod500_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl #does not exist, just following example
+        cp -f /init.etc/keymaps/rhod500_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+        cp -f /init.etc/keymaps/rhod500_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+        cp -f /init.etc/keymaps/rhod500_navi_pad.kl /system/usr/keylayout/gpio-keys.kl #does not exist, just following example
 	;;
     kovsq)
 	echo "USING KOVSKY QWERTY LAYOUT"
-	cp -f /init.etc/keymaps/kovsky-qwerty.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/kovsky-qwerty.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/kovsky-qwerty.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/kovsky-qwerty.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     kovsa)
 	echo "USING KOVSKY AZERTY LAYOUT"
-	cp -f /init.etc/keymaps/kovsky-azerty.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/kovsky-azerty.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/kovsky-azerty.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/kovsky-azerty.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
 	;;
     *)
         echo "USING OLD KEYMAP"
-        cp -f /init.etc/keymaps/oldqwerty_microp-keypad.kcm.bin /data/etc/keymaps/microp-keypad.kcm.bin
-	cp -f /init.etc/keymaps/oldqwerty_microp-keypad.kl /data/etc/keymaps/microp-keypad.kl
-	cp -f /init.etc/keymaps/oldqwerty_raph_navi_pad.kl /data/etc/keymaps/raph_navi_pad.kl
+        cp -f /init.etc/keymaps/oldqwerty_microp-keypad.kcm.bin /system/usr/keychars/microp-keypad.kcm.bin
+	cp -f /init.etc/keymaps/oldqwerty_microp-keypad.kl /system/usr/keylayout/microp-keypad.kl
+	cp -f /init.etc/keymaps/oldqwerty_raph_navi_pad.kl /system/usr/keylayout/gpio-keys.kl
 	;;
 esac
 
-cp -af /init.etc/keymaps/qwerty.kcm.bin /init.etc/keymaps/qwerty.kl /data/etc/keymaps/
 fi
 
-mount /data/etc /etc
-mount --bind /data/etc/keymaps /system/usr/keychars
-mount --bind /data/etc/keymaps /system/usr/keylayout
-mount -o remount,ro /etc
-mount -o remount,ro /system/usr/keychars
-mount -o remount,ro /system/usr/keylayout
+mount -o remount,ro /system
 
 for i in /sys/class/input/input* ; do
         if [ "`cat $i/name`" = "tssc-manager" ] ; then
